-- GrowIt Supabase schema
-- Run this once in the Supabase SQL Editor (Dashboard → SQL Editor → New query → Run).
-- This replaces the local SQLite tables so the app works with persistent hosted data.

create table if not exists public.profile (
  id integer primary key check (id = 1),   -- single-user app: exactly one profile row
  plant_name text not null default 'Sprout',
  xp integer not null default 0,
  streak_days integer not null default 0,
  best_streak integer not null default 0,
  last_active_on text,
  freeze_tokens integer not null default 1,
  last_completed_at bigint,                -- epoch ms, anti-cheat cooldown
  verified_streak integer not null default 0
);

create table if not exists public.habits (
  id bigint generated by default as identity primary key,
  name text not null,
  emoji text not null default '💪',
  category text not null default 'self',
  created_at timestamptz not null default now()
);

create table if not exists public.completions (
  id bigint generated by default as identity primary key,
  habit_id bigint not null references public.habits(id) on delete cascade,
  done_on text not null,                       -- local date YYYY-MM-DD
  honesty text not null default 'full',        -- full | partial | none (anti-cheat)
  note text not null default '',               -- optional proof note
  created_at timestamptz not null default now(),
  unique (habit_id, done_on)
);

create index if not exists idx_completions_habit on public.completions (habit_id);
create index if not exists idx_completions_date on public.completions (done_on);

create table if not exists public.players (
  id bigint generated by default as identity primary key,
  display_name text not null,
  avatar text not null default '🌱',
  xp integer not null default 0,
  streak integer not null default 0,
  best_streak integer not null default 0,
  is_community boolean not null default true
);

create table if not exists public.quests (
  id bigint generated by default as identity primary key,
  key text not null unique,
  title text not null,
  description text not null,
  emoji text not null,
  kind text not null default 'milestone',
  goal integer not null default 1,
  reward_xp integer not null default 10
);

create table if not exists public.quest_claims (
  id bigint generated by default as identity primary key,
  quest_id bigint not null references public.quests(id) on delete cascade,
  claimed_on text not null,
  unique (quest_id, claimed_on)
);

-- seed the single profile row
insert into public.profile (id) values (1)
  on conflict (id) do nothing;

-- Enable RLS (required by Supabase) and allow everything for authenticated/service usage.
-- NOTE: the server uses the service-role key, which bypasses RLS entirely.
insert into public.quests (key, title, description, emoji, kind, goal, reward_xp) values
  ('first_habit', 'First Steps', 'Add your very first habit', '🌱', 'milestone', 1, 10),
  ('three_day', '3 Habits in a Day', 'Complete 3 habits in one day', '💧', 'daily', 3, 20),
  ('streak_3', 'On a Roll', 'Reach a 3-day streak', '🔥', 'milestone', 3, 15),
  ('streak_7', 'Week Warrior', 'Reach a 7-day streak', '⭐', 'milestone', 7, 40),
  ('xp_100', 'Century Club', 'Reach 100 XP', '💯', 'milestone', 100, 30),
  ('xp_300', 'Golden Grower', 'Grow a Golden Fruit Tree (320 XP)', '🌟', 'milestone', 320, 80),
  ('calendar_5', 'Coming Back', 'Show up on 5 different days', '📅', 'milestone', 5, 25)
  on conflict (key) do nothing;

insert into public.players (display_name, avatar, xp, streak, best_streak, is_community) values
  ('Maya 🌸', '🌸', 412, 21, 34, true),
  ('Coach Pete', '🧑‍🦱', 388, 14, 20, true),
  ('Sunny Sally', '🌻', 355, 19, 26, true),
  ('Tiny Tom', '🦖', 301, 9, 15, true),
  ('Grace', '💖', 274, 12, 18, true),
  ('Pixel Pop', '🦄', 240, 8, 11, true),
  ('Nana June', '🧑‍🍳', 210, 17, 21, true),
  ('Skip Skipper', '🚀', 180, 4, 9, true),
  ('Breezy Bea', '🍃', 150, 10, 12, true),
  ('Kiddo Kai', '🎮', 120, 3, 5, true),
  ('Wandering Will', '🧳', 90, 2, 4, true),
  ('Newbie Nova', '🐣', 40, 1, 1, true)
  on conflict do nothing;

-- Register the live user so they appear on the board
insert into public.players (display_name, avatar, xp, streak, best_streak, is_community)
select 'You', '🌱', 0, 0, 0, false
where not exists (select 1 from public.players where is_community = false);

-- enable RLS + policies (all tables)
alter table public.profile enable row level security;
alter table public.habits enable row level security;
alter table public.completions enable row level security;
alter table public.players enable row level security;
alter table public.quests enable row level security;
alter table public.quest_claims enable row level security;

create policy "allow all profile" on public.profile for all using (true) with check (true);
create policy "allow all habits" on public.habits for all using (true) with check (true);
create policy "allow all completions" on public.completions for all using (true) with check (true);
create policy "allow all players" on public.players for all using (true) with check (true);
create policy "allow all quests" on public.quests for all using (true) with check (true);
create policy "allow all quest_claims" on public.quest_claims for all using (true) with check (true);